# Generated by Django 4.2.16 on 2024-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
